### ISSUE TITLE
Issue running tesla_get_partner_auth_token 

### ISSUE THREAD

**Issue by aviadoffer** [fabianhu/tesla_api#1]
First thank you very much for making this project!!!
I followed everything and was able to create an approved app on tesla dev site
I have the tokens keys client id secrets etc

>>> import tesla_api
>>> import config
>>> partner_token = tesla_get_partner_auth_token(config.tesla_client_id, config.tesla_client_secret, AUDIENCE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tesla_get_partner_auth_token' is not defined

What am I doing wrong here?
Also how do I store my tesla_client_id,tesla_client_secret in config.

**Comment by aviadoffer** [comment]
Also in your example:
tesla_register_customer(myTesla) # register new customer (customer must log in and enter code here!)
where is that function? I can't seem to find it.

**Comment by fabianhu** [comment]
Hi there, thank you for the test drive.
From your first question, it seems like your import did not work. Please have a look into the main project, where the usage may be getting clear. [ElectronFluxBalancer](https://github.com/fabianhu/electron-flux-balancer)
Here start from efb_main.py and have a look into the lib directory.
All functions you mention are in the file tesla_api_2024.py.

**Comment by aviadoffer** [comment]
I manage to just run it standalone. so that's good.
I'm getting issues now 

{'error': 'invalid_request', 'error_description': 'Internal server error', 'error_uri': 'https://auth.tesla.com/error/reference/e634eb1d-e875-46b5-bb90-218f4f33b68c-1706038685901'}
Traceback (most recent call last):
  File "C:\Users\Aviad\Sync\Documents\Tesla\New Tesla API\tesla_api-main\tesla_api_2024.py", line 576, in <module>
    r = myT.get_vehicles_list()
  File "C:\Users\Aviad\Sync\Documents\Tesla\New Tesla API\tesla_api-main\tesla_api_2024.py", line 154, in get_vehicles_list
    return self.generic_request(target)
  File "C:\Users\Aviad\Sync\Documents\Tesla\New Tesla API\tesla_api-main\tesla_api_2024.py", line 144, in generic_request
    self.tokens_refresh()
  File "C:\Users\Aviad\Sync\Documents\Tesla\New Tesla API\tesla_api-main\tesla_api_2024.py", line 98, in tokens_refresh
    token_data["expiry_time"] = (datetime.datetime.now() + datetime.timedelta(seconds=token_data.get('expires_in'))).isoformat()
TypeError: unsupported type for timedelta seconds component: NoneType

All I'm trying to do for now is get_vehicles_list. (your file is modified)

**Comment by fabianhu** [comment]
Looks like the server complains 
"'invalid_request', 'error_description': 'Internal server error' ..."
and my code does not understand the answer. 
Error handling is not yet implemented, I see - noted this.
Did you do all steps in tesla_register_process() before and step # 4 completes successfully?

**Comment by aviadoffer** [comment]
I don't understand how to run step 4 or 5. those functions you mentioned there are no where to be found.
I appreciate your help!!

**Comment by fabianhu** [comment]
Sorry that Tesla made it a little more complicated - Go to the file tesla_api/tesla_api_2024.py line 491 and look for the function tesla_register_process(). Follow the comments here - should be in line with the instructions [here](https://developer.tesla.com/docs/fleet-api#overview)
After completing # 4, your tokens are stored to file and the call to get_vehicles_list() should work.

**Comment by aviadoffer** [comment]
Thanks much for your quick responses. I will try it tonight/tomorrow and report back.

**Comment by aviadoffer** [comment]
OK I see whats it's doing now, it will open a browser with the URI to register, but when it opens it I get this error:
![image](https://github.com/fabianhu/tesla_api/assets/8140249/d54c87f9-08ed-4c62-a9c8-55cb5fadc571)

**Comment by aviadoffer** [comment]
OMG it worked! damn damn! thank you so much. this is great! I am trying to think how to improve the documentation, I will post back after the excitement

**Comment by aviadoffer** [comment]
One thing I'm missing for now is car['vehicle_state']['homelink_nearby']
I use this to know if the car is at home (for charging). seems like it's not part of the car object now :(

**Comment by aviadoffer** [comment]
oh, found it under conn.request("GET", f"/api/1/vehicles/{vin}/vehicle_data", payload, headers) !! life is good.

**Comment by fabianhu** [comment]
Great, then I will close this. Thanks for your test drive!

**Comment by fabianhu** [comment]
@aviadoffer see the test drive implementation [here](https://github.com/fabianhu/tesla_api_example)
