### ISSUE TITLE
need more instructions to get started

### ISSUE THREAD

**Issue by JanJaapKo** [fabianhu/tesla_api#2]
For me the instructions to get started plus what I could achieve are not clear. Also the installation instruction are not clear to me (I'm no expert but not a noob either....). Below some findings that I hope you can use:

My status so far: I have developed a [python plugin](https://github.com/JanJaapKo/TeslaDomoticz) for Domoticz home automation (and several other plugins before the Tesla integration). This plugin is in essence a Domoticz wrapper around the [TeslaPy library](https://github.com/tdorssers/TeslaPy/). As TeslaPy does not support the Fleet API I'm looking for a replacement for which this project seems a good fit (want to be able to read data from my model Y and sends commands to it).

So far I got stuck at the step of installing the go language:
```
sudo apt install golang
go get ./...
go build ./...
go install ./...
```
(it complained about missing dependencies:
```
pi@huiskamer:~/scripts/tesla_api/tesla-control/vehicle-command/cmd/tesla-control $ go build .
../../pkg/account/account.go:5:2: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.15/src/crypto/ecdh)
../../pkg/account/account.go:6:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
../../pkg/cli/config.go:55:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)
```

However it is not clear to me if this is needed at all. 

So I really like the detailed way the TDossers has made both the installation instructions as well as the tesla_prepare.py module that handles the initial registration and additionally gives a basic module that works and spits out some data. I can take it from there.

Concrete things that confuse me:
- the installation section of the readme.md
- then the registration process also gives me some questions. Not sure if it is in the right place, sequentially?
- are the code snippets in the registration section part of a python module or CLI instructions?
- the instructions for the go language come last, but would they not be needed first? They are also rather limited, for example 'build the go language' should at least have a reference to a site where it is explained in more detail (next steps are a good example of how to document)

I hope these comments can help you to make this library better (they sure aren't meant as criticism).

Btw comments on [issue 156](https://github.com/tdorssers/TeslaPy/issues/156) seem to suggest you don't need to build the go stuff?

**Comment by fabianhu** [comment]
Hi!, thanks for your input!
Only some quick comments, until I have time, to dive deeper into this:
The Go package is only needed for sending commands. 
The whole registration process should work without Go.
The comments out of issue 156 seem to be the old command format. This will not work for newer cars - at least not for long.
@JanJaapKo I just updated the readme. 
Please read through it and let me know, if you get stuck at a specific step in a new issue.  
I tend to close this issue here.

**Comment by JanJaapKo** [comment]
Hi,
As a first step, could you describe the things that would use the fleet api just for fetching data, as aviadoffer said he did in issue 156?

Additionally, if I understand Tesla auth instructions correctly, I need to have a public domain. Guessing my public IP isn't going to do it. Can you confirm? Any (lowcost/free) suggestions?

**Comment by fabianhu** [comment]
Just follow the README.md and skip the Go build.  I just updated the file and also the comments in the library.
Unfortunately the whole process is quite complicated.
It took me quite some time to figure it out.

Yes, you need an own domain registered. 
You need ssl support too. Don't go too cheap. 
As you are presumably driving a Tesla, you can invest some saved gas-money ;)

**Comment by fabianhu** [comment]
closed [with this commit](https://github.com/fabianhu/tesla_api/commit/b270550f22792c754b56e30f149249ddc95a0e2f)

**Comment by fabianhu** [comment]
@JanJaapKo see the test drive implementation [here](https://github.com/fabianhu/tesla_api_example)
