### ISSUE TITLE
Stuck at step 4

### ISSUE THREAD

**Issue by DeLN0** [fabianhu/tesla_api#3]
Hi @fabianhu and ty for this project

I'm trying to get this to run.
In tesla_register_process i do steps 1-3, everything is ok so far.
Then, for step 4, i open the url from the qr code on my iPhone, this in turn opens my Tesla app and i get:

![IMG_8815](https://github.com/fabianhu/tesla_api/assets/157612876/c548cf92-d1de-4dbc-8e49-9d055a646a90)

Also, for step # 2c (_r = tesla_register_partner_account(partner_token, config.tesla_redirect_domain) # is only needed once!) the first time i ran it, i got this:

![IMG_8812](https://github.com/fabianhu/tesla_api/assets/157612876/a9143dff-9c86-4c8d-b26a-1c1f1763e727)

This only happened the first time, the following times i ran tesla_register_partner_account, it didn't ask me for consent anymore, maybe i didn't do something right the first time and that is the problem?

What do you think is the problem?

**Comment by fabianhu** [comment]
I see, I have to do a minimal app, which uses this library.

Only two ideas without testing myself:
- Try running tesla_register_partner_account again and post the result. (anonymize your data, of course).

- Log into your normal tesla account: In account settings -> security check for 3rd party apps - maybe, you can remove it and try again.

I will try to register a second app, so that I can test a minimal app.

**Comment by DeLN0** [comment]
Hi @fabianhu

I followed your advice ('Log into your normal tesla account: In account settings -> security check for 3rd party apps - maybe, you can remove it and try again.')

Now i get the prompt to allow access to to app again.
One step closer but still not working (same error from the Tesla app 'Unable to Share Vehicle
This third party isn't registered with Tesla. We can't grant them access at this time.')

I think the problem is the following:
In my Fleet API app request i selected the following scopes:

![IMG_8846](https://github.com/fabianhu/tesla_api/assets/157612876/ecf3fcb9-18c8-4bbc-9d5b-1ef70d64f90b)

But the prompt to allow access to app shows the ONLY following scopes:

![IMG_8844](https://github.com/fabianhu/tesla_api/assets/157612876/7f037dd0-6982-4eef-8b5d-e96fdd666c56)

So scope Vehicle Charging Management is missing!

Taking this further, I replaced your line 
`url = f"https://auth.tesla.com/oauth2/v3/authorize?&client_id={myTesla.client_id}&locale=de-DE&prompt=login&redirect_uri={REDIRECT_URI}&response_type=code&scope=vehicle_device_data%20offline_access%20vehicle_charging_cmds&state={random_state}" `
with line 
`url = f"https://auth.tesla.com/oauth2/v3/authorize?&client_id={myTesla.client_id}&locale=en-EU&prompt=login&redirect_uri={REDIRECT_URI}&response_type=code&scope=offline_access%20vehicle_device_data%20vehicle_cmds%20vehicle_charging_cmd&state={random_state}" `

Still not working but i guess it has something to do with the scopes, as the requested scopes do not cover all scopes granted for the app.

Any thoughts?

**Comment by DeLN0** [comment]
I managed to get this to work.

In your tesla_api_2024.py file i replaced 2 lines:
replace
`_r = tesla_register_partner_account(partner_token, config.tesla_redirect_domain) # is only needed once!`
with
`_r = tesla_register_partner_account(partner_token, config.tesla_redirect_domain.replace("https://", "")) # is only needed once!`
and replace
`url=f"https://tesla.com/_ak/{config.tesla_redirect_domain.}"`
with
`url=f"https://tesla.com/_ak/{config.tesla_redirect_domain.replace('https://', '')}"`

And also, make sure the following lines match the scopes you are allowed to request (the scopes you checked when creating your Application Access Request):
`"scope": "openid offline_access vehicle_device_data vehicle_cmds vehicle_charging_cmds",`
and 
`url = f"https://auth.tesla.com/oauth2/v3/authorize?&client_id={myTesla.client_id}&locale=en-EU&prompt=login&redirect_uri={REDIRECT_URI}&response_type=code&scope=openid%20offline_access%20vehicle_device_data%20vehicle_cmds%20vehicle_charging_cmds&state={random_state}"`

**Comment by fabianhu** [comment]
@DeLN0 
Thank you, commit addressing the issues coming up.

**Comment by fabianhu** [comment]
@DeLN0 see the test drive implementation [here](https://github.com/fabianhu/tesla_api_example)
