### ISSUE TITLE
error with BLE and note remote SSH connection

### ISSUE THREAD

**Issue by kurb77** [fabianhu/tesla_api#6]
Hello,
i think you didn't code the case 'i use BLE, but i don't use the remote ssh connection' 

with this config.py 
tesla_ble = True # True if commands to be sent via BLE
#tesla_remote = ''

` File "/root/tesla_api_example/main.py", line 295, in <module>
    myTesla.cmd_wakeup(vin)
  File "/root/tesla_api_example/lib/tesla_api/tesla_api_2024.py", line 209, in cmd_wakeup
    return self.tesla_command("wake",_vin, config.tesla_ble, config.tesla_remote, "vcsec")
                                                             ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'tesla_remote'
`
or with this config.py

tesla_ble = True # True if commands to be sent via BLE
tesla_remote = ''

ssh  './tesla-control -ble -domain vcsec -command-timeout 10s -key-file ./relay_priv.pem -vin XP7YGCEL99999999 wake'

thank you

**Comment by fabianhu** [comment]
Thank you for the hint.
When you set it to 
```python
tesla_remote = None
```
it should work.

**Comment by fabianhu** [comment]
updated example [here](https://github.com/fabianhu/tesla_api_example/commit/57315acdfe1e169da15609142b60c4fc8f39929d)

**Comment by kurb77** [comment]
great,
thank you
